name: Update badges

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email "vojtech@bakaj.cz"
      - run: git config --global user.name "Technical user"
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: '${{ secrets.GH_TOKEN }}'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run test:coverage
      - run: npm link
      - run: badge-forge generate
      - run: git add badges
      - run: git commit --allow-empty -m 'Update badges' -- badges
      - run: git push origin

